version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: tazzkeruser
      POSTGRES_PASSWORD: tazzkerpass
      POSTGRES_DB: TazzkerDb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: TazzkerAPI/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Host=db;Database=TazzkerDb;Username=tazzkeruser;Password=tazzkerpass
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: Tazzker.Client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  dbdata:
